# src/main/resources/application.yml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyhub?serverTimezone=Asia/Seoul
    username: root
    password: 246126
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false

server:
  port: 8080
