spring:
  # 운영 환경 데이터베이스 설정 (AWS RDS MySQL)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 운영 환경 커넥션 풀 설정
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # JPA 설정 (운영 환경)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false  # 운영 환경에서는 SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false  # SQL 포맷팅 비활성화
        dialect: org.hibernate.dialect.MySQLDialect
        # 성능 최적화
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        # 2차 캐시 비활성화
        cache:
          use_second_level_cache: false
        # 통계 정보 비활성화
        generate_statistics: false

  # H2 콘솔 비활성화 (운영 환경)
  h2:
    console:
      enabled: false

  # 운영 환경 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

# 운영 환경 로깅 설정
logging:
  level:
    dev.kang.studyhub: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: WARN
  file:
    name: logs/studyhub.log
    max-size: 100MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 운영 환경 서버 설정
server:
  port: ${PORT:8080}
  # 보안 헤더 설정
  servlet:
    session:
      timeout: 30m
  # 운영 환경 에러 페이지 설정
  error:
    include-stacktrace: never
    include-message: always

# 운영 환경 Cloudinary 설정
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# 운영 환경 관리자 계정 설정
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD} 